#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${OPENCLAW_ENV_FILE:-${ROOT_DIR}/.env}"

usage() {
  cat <<'EOF'
Usage: bootstrap-startup.sh [start|status|stop|restart|recreate|rebuild] [--reset-resources]

Commands:
  start      Start services without rebuilding, then run phase-1 middleware init.
  status     Show compose service status.
  stop       Stop compose services.
  restart    Restart compose services.
  recreate   Recreate compose services without rebuilding, then run phase-1 middleware init.
  rebuild    Rebuild images, recreate services, then run phase-1 middleware init.

Options:
  --reset-resources
             Delete and recreate phase-1 middleware resources during init.
             Applies only to start, recreate, and rebuild. The default is to
             leave existing resources untouched.
EOF
}

load_env_file() {
  if [[ ! -f "$ENV_FILE" ]]; then
    echo "missing env file: $ENV_FILE" >&2
    exit 1
  fi

  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
}

ensure_host_dirs() {
  : "${OPENCLAW_CONFIG_DIR_HOST:=${HOME}/.openclaw-docker/state}"
  : "${OPENCLAW_WORKSPACE_DIR_HOST:=${HOME}/ai-agent}"
  : "${OPENCLAW_AUTH_PROFILE_SECRET_DIR_HOST:=${HOME}/.openclaw-docker/auth}"
  : "${OPENCLAW_SSH_DIR_HOST:=${HOME}/.openclaw-docker/ssh}"
  : "${OPENCLAW_VSCODE_SERVER_DIR_HOST:=${HOME}/.openclaw-docker/vscode-server}"
  : "${OPENCLAW_VSCODE_CODEX_DIR_HOST:=${HOME}/.openclaw-docker/vscode-codex}"
  : "${EDGEVISION_ENV_FILE:=${ROOT_DIR}/volume/edge-vision-ops/env/edge-vision.generated.env}"

  mkdir -p \
    "$OPENCLAW_CONFIG_DIR_HOST" \
    "$OPENCLAW_WORKSPACE_DIR_HOST" \
    "$OPENCLAW_VSCODE_SERVER_DIR_HOST" \
    "$OPENCLAW_VSCODE_CODEX_DIR_HOST" \
    "$(dirname "$EDGEVISION_ENV_FILE")"
  install -d -m 700 \
    "$OPENCLAW_AUTH_PROFILE_SECRET_DIR_HOST" \
    "$OPENCLAW_SSH_DIR_HOST"
  export OPENCLAW_CONFIG_DIR_HOST
  export OPENCLAW_WORKSPACE_DIR_HOST
  export OPENCLAW_AUTH_PROFILE_SECRET_DIR_HOST
  export OPENCLAW_SSH_DIR_HOST
  export OPENCLAW_VSCODE_SERVER_DIR_HOST
  export OPENCLAW_VSCODE_CODEX_DIR_HOST
  export EDGEVISION_ENV_FILE
}

normalize_tenant() {
  local value="$1"
  TENANT_VALUE="$value" python3 - <<'PY'
import os
import re

value = os.environ.get("TENANT_VALUE", "default").strip().lower()
value = re.sub(r"[^a-z0-9]+", "-", value).strip("-")
print(value or "default")
PY
}

tenant_suffix() {
  local value="$1"
  value="${value//-/_}"
  printf '%s' "$value"
}

redis_db_for_tenant() {
  local tenant_slug="$1"
  local databases="${2:-256}"
  TENANT_SLUG="$tenant_slug" REDIS_DATABASES="$databases" python3 - <<'PY'
import os
import hashlib

tenant = os.environ["TENANT_SLUG"].encode("utf-8")
databases = int(os.environ.get("REDIS_DATABASES", "256"))
if databases <= 0:
    databases = 256
digest = hashlib.sha256(tenant).digest()
value = int.from_bytes(digest[:4], "big") % databases
print(value)
PY
}

prepare_business_env() {
  local tenant_value
  local tenant_suffix_value

  tenant_value="$(normalize_tenant "${OPENCLAW_TENANT:-default}")"
  tenant_suffix_value="$(tenant_suffix "$tenant_value")"

  export OPENCLAW_TENANT="$tenant_value"

  : "${OPENCLAW_POSTGRES_DB:=openclaw_${tenant_suffix_value}}"
  : "${OPENCLAW_POSTGRES_USER:=openclaw}"
  : "${OPENCLAW_POSTGRES_PASSWORD:=openclaw}"
  : "${OPENCLAW_MINIO_BUCKET:=openclaw-${tenant_value}}"
  : "${OPENCLAW_RABBITMQ_VHOST:=/openclaw-${tenant_value}}"
  : "${OPENCLAW_RABBITMQ_USER:=openclaw}"
  : "${OPENCLAW_RABBITMQ_PASSWORD:=openclaw-rabbitmq}"
  : "${OPENCLAW_REDIS_DATABASES:=256}"
  : "${OPENCLAW_REDIS_DB:=$(redis_db_for_tenant "$tenant_value" "$OPENCLAW_REDIS_DATABASES")}"
  : "${OPENCLAW_REDIS_KEY_PREFIX:=${tenant_value}:}"

  : "${OPENCLAW_REDIS_URL:=redis://redis:6379/${OPENCLAW_REDIS_DB}}"

  export OPENCLAW_POSTGRES_DB
  export OPENCLAW_POSTGRES_USER
  export OPENCLAW_POSTGRES_PASSWORD
  export OPENCLAW_MINIO_BUCKET
  export OPENCLAW_RABBITMQ_VHOST
  export OPENCLAW_RABBITMQ_USER
  export OPENCLAW_RABBITMQ_PASSWORD
  export OPENCLAW_REDIS_DATABASES
  export OPENCLAW_REDIS_DB
  export OPENCLAW_REDIS_KEY_PREFIX
  export OPENCLAW_REDIS_URL
}

edgevision_postgres_dsn() {
  printf 'postgres://%s:%s@%s:%s/%s?sslmode=%s' \
    "$OPENCLAW_POSTGRES_USER" \
    "$OPENCLAW_POSTGRES_PASSWORD" \
    "${EDGEVISION_POSTGRES_HOST:-postgres}" \
    "${EDGEVISION_POSTGRES_PORT:-5432}" \
    "$OPENCLAW_POSTGRES_DB" \
    "${EDGEVISION_POSTGRES_SSL_MODE:-disable}"
}

edgevision_env_escape() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '%s' "$value"
}

write_edgevision_env_file() {
  local tmp_file

  tmp_file="$(mktemp)"
  {
    printf '%s\n' '# generated by bootstrap-startup.sh; do not edit by hand'
    printf 'EDGEVISION_POSTGRES_HOST="%s"\n' "$(edgevision_env_escape 'postgres')"
    printf 'EDGEVISION_POSTGRES_PORT="%s"\n' "$(edgevision_env_escape '5432')"
    printf 'EDGEVISION_POSTGRES_USER="%s"\n' "$(edgevision_env_escape "$OPENCLAW_POSTGRES_USER")"
    printf 'EDGEVISION_POSTGRES_PASSWORD="%s"\n' "$(edgevision_env_escape "$OPENCLAW_POSTGRES_PASSWORD")"
    printf 'EDGEVISION_POSTGRES_DB_NAME="%s"\n' "$(edgevision_env_escape "$OPENCLAW_POSTGRES_DB")"
    printf 'EDGEVISION_POSTGRES_SSL_MODE="%s"\n' "$(edgevision_env_escape 'disable')"
    printf 'EDGEVISION_POSTGRES_DSN="%s"\n' "$(edgevision_env_escape "$(edgevision_postgres_dsn)")"
    printf 'EDGEVISION_REDIS_ADDR="%s"\n' "$(edgevision_env_escape 'redis:6379')"
    printf 'EDGEVISION_REDIS_DB="%s"\n' "$(edgevision_env_escape "$OPENCLAW_REDIS_DB")"
    printf 'EDGEVISION_REDIS_PASSWORD="%s"\n' "$(edgevision_env_escape '')"
    printf 'EDGEVISION_MINIO_ENDPOINT="%s"\n' "$(edgevision_env_escape "${OPENCLAW_MINIO_ENDPOINT:-http://minio:9000}")"
    printf 'EDGEVISION_MINIO_ACCESS_KEY_ID="%s"\n' "$(edgevision_env_escape "${OPENCLAW_MINIO_ROOT_USER:-openclaw}")"
    printf 'EDGEVISION_MINIO_SECRET_ACCESS_KEY="%s"\n' "$(edgevision_env_escape "${OPENCLAW_MINIO_ROOT_PASSWORD:-openclaw-minio}")"
    printf 'EDGEVISION_MINIO_BUCKET="%s"\n' "$(edgevision_env_escape "${OPENCLAW_MINIO_BUCKET}")"
    printf 'EDGEVISION_MINIO_USE_SSL="%s"\n' "$(edgevision_env_escape "${OPENCLAW_MINIO_USE_SSL:-false}")"
    printf 'EDGEVISION_RABBITMQ_VHOST="%s"\n' "$(edgevision_env_escape "$OPENCLAW_RABBITMQ_VHOST")"
    printf 'EDGEVISION_ZLM_API_URL="%s"\n' "$(edgevision_env_escape 'http://zlmediakit')"
    printf 'EDGEVISION_ZLM_VHOST="%s"\n' "$(edgevision_env_escape '__defaultVhost__')"
  } >"$tmp_file"
  mv "$tmp_file" "$EDGEVISION_ENV_FILE"
  chmod 600 "$EDGEVISION_ENV_FILE"
}

load_edgevision_env_file() {
  if [[ -f "$EDGEVISION_ENV_FILE" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$EDGEVISION_ENV_FILE"
    set +a
  fi
}

prepare_runtime_identity() {
  : "${OPENCLAW_NODE_UID:=$(id -u)}"
  : "${OPENCLAW_NODE_GID:=$(id -g)}"
  : "${OPENCLAW_RUNTIME_UID:=${OPENCLAW_NODE_UID}}"
  : "${OPENCLAW_RUNTIME_GID:=${OPENCLAW_NODE_GID}}"
  : "${OPENCLAW_SHARED_GROUP:=evp}"

  if [[ -z "${OPENCLAW_SHARED_GID:-}" && -n "$OPENCLAW_SHARED_GROUP" ]]; then
    OPENCLAW_SHARED_GID="$(getent group "$OPENCLAW_SHARED_GROUP" | cut -d: -f3 || true)"
  fi

  export OPENCLAW_NODE_UID
  export OPENCLAW_NODE_GID
  export OPENCLAW_RUNTIME_UID
  export OPENCLAW_RUNTIME_GID
  export OPENCLAW_SHARED_GROUP
  export OPENCLAW_SHARED_GID
}

compose_cmd() {
  docker compose \
    --env-file "$ENV_FILE" \
    -f "${ROOT_DIR}/compose.openclaw.gpu.yml" \
    -f "${ROOT_DIR}/compose.openclaw.dri.yml" \
    -f "${ROOT_DIR}/compose.openclaw.yml" \
    "$@"
}

prepare_env() {
  load_env_file
  ensure_host_dirs
  prepare_business_env
  write_edgevision_env_file
  load_edgevision_env_file
  prepare_runtime_identity
}

run_phase1_init() {
  local reset_resources="$1"
  local init_args=()

  if [[ "$reset_resources" == "true" ]]; then
    init_args+=(--reset-resources)
  fi

  OPENCLAW_ENV_FILE="$ENV_FILE" bash "${ROOT_DIR}/init-phase1-middleware.sh" "${init_args[@]}"
}

main() {
  local command="start"
  local reset_resources=false

  if [[ $# -gt 0 ]]; then
    case "$1" in
      start|status|stop|restart|recreate|rebuild|-h|--help|help)
        command="$1"
        shift
        ;;
      --reset-resources)
        command="start"
        ;;
      *)
        echo "unknown command: $1" >&2
        usage >&2
        exit 2
        ;;
    esac
  fi

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --reset-resources)
        reset_resources=true
        ;;
      -h|--help|help)
        usage
        exit 0
        ;;
      *)
        echo "unknown argument: $1" >&2
        usage >&2
        exit 2
        ;;
    esac
    shift
  done

  if [[ "$reset_resources" == "true" && "$command" != "start" && "$command" != "recreate" && "$command" != "rebuild" ]]; then
    echo "--reset-resources can only be used with start, recreate, or rebuild" >&2
    exit 2
  fi

  case "$command" in
    start)
      prepare_env
      compose_cmd up -d --no-build
      run_phase1_init "$reset_resources"
      ;;
    status)
      prepare_env
      compose_cmd ps
      ;;
    stop)
      prepare_env
      compose_cmd stop
      ;;
    restart)
      prepare_env
      compose_cmd restart
      ;;
    recreate)
      prepare_env
      compose_cmd up -d --no-build --force-recreate
      run_phase1_init "$reset_resources"
      ;;
    rebuild)
      prepare_env
      compose_cmd up -d --build --force-recreate
      run_phase1_init "$reset_resources"
      ;;
    -h|--help|help)
      usage
      ;;
    *)
      echo "unknown command: $command" >&2
      usage >&2
      exit 2
      ;;
  esac

}

main "$@"
